
version: 2

models:
  - name: daily_production_by_resource
    description: "For each day, how much material was moved through each resource"
    columns:
      - name: date
        description: "The day of aggregation"
        tests:
          - not_null
      - name: resource_id
        description: "The id of the resource which was used. Can be joined to mes_resources to get further information."
        tests:
          - not_null
      - name: quantity
        description: "The amount of material moved through the resource on the given day. Note that this is tracked in the primary UOM which effectively makes this table useless for any resource which operates in multiple UOMs."
        tests:
          - not_null

tests:
  - name: check_yield_over_100
    description: "Check that the yield is not over 100% on any record in the yield reports"

sources:
  - name: chocolate-factory
    database: chocolate-factory
    schema: public
    tables:
      - name: mes_resources
      - name: mes_complete_logs
      - name: mes_scrap_logs
      - name: erp_work_orders
      - name: erp_products
      - name: erp_routes
      - name: mes_operations

